name: lupape
favicon: null
layout_spectrum: 0.95375
typography_spectrum: 0.2842
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: lupape
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#cbb1be'
    - '#a694b8'
    - '#0000ff'
    - '#ff8080'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.3727598
purpose: []
