name: lupape
favicon: null
layout_spectrum: 1
typography_spectrum: 0.41719
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#125688'
    - '#B4EA0D'
    - '#25272A'
    - '#A5A7AA'
  brandStrength: 0.5053763
  lightness: 0.2455197
  saturation: 0.6451613
  rhythmicContrast: 0.8458781
purpose: []
